# Generated by Django 4.1 on 2024-10-03 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_rename_image_movie_movie_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='movie_image',
            new_name='image',
        ),
    ]
